2019-11-26 13:36:59,968 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:50]
2019-11-26 13:43:27,126 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:50]
2019-11-26 13:49:20,315 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:50]
2019-11-26 14:10:32,132 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:50]
2019-11-26 14:29:04,022 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:50]
2019-11-26 17:03:21,244 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:53]
2019-11-26 17:24:55,699 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:56]
2019-11-26 17:25:03,559 ERROR: Exception on / [GET] [in c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\projects\microblog\app\routes.py", line 30, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Samuel\projects\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\Samuel\projects\microblog\app\templates\index.html", line 17, in root
  File "C:\Users\Samuel\projects\microblog\app\templates\base.html", line 14, in root
    <div class="navbar-header">
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 90, in block_body
  File "C:\Users\Samuel\projects\microblog\app\templates\base.html", line 54, in block_navbar
    {% endblock %}
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'logout'. Did you mean 'auth.logout' instead?
2019-11-26 17:28:47,084 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:56]
2019-11-26 17:29:00,983 ERROR: Exception on /index [GET] [in c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_login\login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask_login\utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\samuel\projects\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2019-11-26 17:31:09,589 INFO: Microblog startup [in C:\Users\Samuel\projects\microblog\app\__init__.py:56]
